version: '2'
linters:
  default: all
  enable:
    - exhaustruct_v5
    - gomodguard_v2
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - funlen
    - gocognit
    - goconst
    - gocritic
    - godox
    - gomodguard
    - gosec
    - mnd
    - nestif
    - noctx
    - noinlineerr
    - tagliatelle
    - testpackage
    - wrapcheck
    - wsl
  settings:
    exhaustruct_v5:
      ignore-patterns:
        - github.com\/urfave\/cli\/v[0-9]+\..+
        - github.com\/3lvia\/cli\/pkg\/auth\.AzLoginCommandOptions
        - github.com\/3lvia\/cli\/pkg\/build\.GenerateDockerfileOptions
        - github.com\/3lvia\/cli\/pkg\/command\.RunOptions
        - github.com\/3lvia\/cli\/pkg\/command\.Output
        - github.com\/3lvia\/cli\/pkg\/style\.PrintOptions
    staticcheck:
      checks:
        - ST1000
        - ST1001
        - ST1003
        - ST1006
        - ST1008
        - ST1011
        - ST1012
        - ST1013
        - ST1015
        - ST1016
        - ST1017
        - ST1018
        - ST1019
        - ST1020
        - ST1021
        - ST1022
        - ST1023
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - varnamelen
        text: parameter name 'c' is too short for the scope of its usage
      - linters:
          - gochecknoglobals
        text: Dotnet.* is a global variable
      - linters:
          - gochecknoglobals
        text: Python.* is a global variable
      - linters:
          - gochecknoglobals
        text: Go.* is a global variable
      - linters:
          - gochecknoglobals
        text: Templates is a global variable
      - linters:
          - gochecknoglobals
        text: Languages is a global variable
      - linters:
          - revive
        text: 'exported: func name will be used as scan.ScanImage by other packages, and that stutters; consider calling this Image'
      - linters:
          - forbidigo
        text: use of `fmt.Println` forbidden by pattern
      - linters:
          - revive
        text: 'error-strings: error strings should not be capitalized or end with punctuation or a newline'
      - linters:
          - revive
        text: 'var-naming: avoid meaningless package names'
      - linters:
          - godoclint
        text: godoc should start with symbol name
      - linters:
          - revive
        text: 'var-naming: avoid package names that conflict with Go standard library package names'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
