name: 'Setup 3lv'
description: 'Sets up the Elvia CLI on your GitHub Actions runner.'
inputs:
  version:
    description: 'The version of 3lv to install.'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Download 3lv CLI
      shell: bash
      run: |
        version='${{ inputs.version }}'
        if [[ $version == 'latest' ]]; then
          version=$(gh release list -R 3lvia/cli --json name,isLatest -q '.[] | select(.isLatest == true) | .name')
        fi

        curl -sSL "https://github.com/3lvia/cli/releases/download/$version/3lv-linux-amd64.tar.gz"
        curl -sSL "https://github.com/3lvia/cli/releases/download/$version/3lv-linux-amd64.tar.gz.md5"
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Verify 3lv CLI checksum
      shell: bash
      run: md5sum -c 3lv-linux-amd64.tar.gz.md5

    - name: Install 3lv CLI
      shell: bash
      run: ./scripts/install.sh 3lv-linux-amd64.tar.gz
