name: 'Setup 3lv'
description: 'Sets up the Elvia CLI on your GitHub Actions runner.'
inputs:
  version:
    description: 'The version of 3lv to install.'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Setup the 3lv CLI
      shell: bash
      run: |
        # Setup the 3lv CLI
        if [[ '${{ inputs.version }}' == 'latest' ]]; then
          version=$(gh release list -R 3lvia/cli --json name,isLatest -q '.[] | select(.isLatest == true) | .name')
        else
          version='v${{ inputs.version }}'
        fi

        gh release download -R 3lvia/cli "$version" --pattern "$BINARY_TARBALL*"
        md5sum -c "$BINARY_TARBALL.md5"
        tar -xzvf "$BINARY_TARBALL"
        sudo install -Dm755 -t /usr/bin 3lv
      env:
        GH_TOKEN: ${{ github.token }}
        BINARY_TARBALL: '3lv-linux-amd64.tar.gz'
