name: Analyze, test and lint

on:
  pull_request:
    branches: [trunk]

jobs:
  analyze:
    name: Analyze
    runs-on: elvia-runner
    permissions:
      actions: read
      contents: read
      security-events: write
    concurrency:
      group: '${{ github.workflow }}-${{ github.event_name }}-analyze'
      cancel-in-progress: true
    steps:
      - uses: 3lvia/core-github-actions-templates/analyze@trunk
        with:
          language: 'go'

  test:
    name: Test
    runs-on: elvia-runner
    concurrency:
      group: '${{ github.workflow }}-${{ github.event_name }}-test'
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: 'go.sum'
          go-version-file: 'go.mod'

      - name: Run tests
        run: make test

  lint:
    name: Lint
    runs-on: elvia-runner
    concurrency:
      group: '${{ github.workflow }}-${{ github.event_name }}-lint'
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: 'go.sum'
          go-version-file: 'go.mod'

      - name: Run linter
        run: make lint
