name: Analyze, build, test and lint

on:
  pull_request:
    branches: [trunk]
    paths-ignore:
      - 'README.md'
      - 'setup/action.yml'

jobs:
  analyze:
    name: Analyze
    runs-on: elvia-runner
    permissions:
      actions: read
      contents: read
      security-events: write
    concurrency:
      group: '${{ github.workflow }}-${{ github.event_name }}-analyze'
      cancel-in-progress: true
    steps:
      - uses: 3lvia/core-github-actions-templates/analyze@trunk
        with:
          language: 'go'

  build-test:
    name: Build & test
    runs-on: elvia-runner
    concurrency:
      group: '${{ github.workflow }}-${{ github.event_name }}-build'
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: 'go.sum'
          go-version-file: 'go.mod'

      - name: Run tests
        run: go test -v ./...

      - name: Build
        run: ./scripts/build.sh

  lint:
    name: Lint
    runs-on: elvia-runner
    concurrency:
      group: '${{ github.workflow }}-${{ github.event_name }}-lint'
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: 'go.sum'
          go-version-file: 'go.mod'

      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          args: '--timeout=5m ./...'
