name: Build and release

on:
  push:
    branches: [trunk]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'install.sh'
  pull_request:
    branches: [trunk]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'install.sh'

jobs:
  build:
    name: Build
    runs-on: elvia-runner
    strategy:
      matrix:
        os: [linux, macos]
        arch: [amd64]
        include:
          - os: macos
            arch: arm64
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'go.mod'

      - name: Package binaries
        shell: bash
        run: make "package-$BUILD_OS-$BUILD_ARCH"
        env:
          BUILD_OS: ${{ matrix.os }}
          BUILD_ARCH: ${{ matrix.arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: '3lv-${{ matrix.os }}-${{ matrix.arch }}'
          path: 'dist/package/*'

  draft-release:
    name: Draft release
    needs: [build]
    runs-on: elvia-runner
    if: ${{ github.event_name == 'push' }}
    outputs:
      version-tag: ${{ steps.get-version.outputs.version_tag }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Resolve version
        id: get-version
        run: |
          version=$(cat VERSION)
          echo "VERSION_TAG=v$version" | tee -a "$GITHUB_ENV" "$GITHUB_OUTPUT"
          echo "MAJOR_VERSION_TAG=v$(echo $version | cut -d. -f1)" >> "$GITHUB_ENV"

      - name: Create draft of release if new version
        id: create-draft-release
        run: |
          latest_version=$(gh release list --json name,isLatest -q '.[] | select(.isLatest == true) | .name')
          if [[ "$latest_version" == "$VERSION_TAG" ]]; then
            echo "Version already released."
            exit 0
          fi

          latest_draft_version=$(gh release list --json name,isDraft -q 'first(.[] | select(.isDraft == true) | .name)')
          if [[ "$latest_draft_version" == "$VERSION_TAG" ]]; then
            echo "Draft already created."
            exit 0
          fi

          gh release create "$VERSION_TAG" --generate-notes --draft
        env:
          GH_TOKEN: ${{ github.token }}

  upload-binaries:
    name: Upload binaries
    needs: [draft-release]
    runs-on: elvia-runner
    if: ${{ github.event_name == 'push' }}
    strategy:
      matrix:
        os: [linux, macos]
        arch: [amd64]
        include:
          - os: macos
            arch: arm64
      fail-fast: false
    env:
      VERSION_TAG: ${{ needs.draft-release.outputs.version-tag }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Download build artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: '3lv-${{ matrix.os }}-${{ matrix.arch }}'

      - name: Upload binaries if not already uploaded
        run: |
          version=$(echo "$VERSION_TAG" | cut -c 2-)
          package_name="3lv-$version-$MATRIX_OS-$MATRIX_ARCH"
          number_of_binaries=$(gh release view "$VERSION_TAG" \
                                --json assets \
                                | jq -r --arg package_name "$package_name" '.[] | map(select(.name | contains($package_name))) | length')

          # One binary and one checksum file per arch/os combo
          if [[ "$number_of_binaries" -gt 1 ]]; then
            echo "Binaries already uploaded."
            exit 0
          fi

          # Special case for macOS binaries being named differently from their architecture (darwin)
          if [[ "$MATRIX_OS" == 'macos' ]]; then
            mv "3lv-$version-darwin-$MATRIX_ARCH.tar.gz" "$package_name.tar.gz"
            mv "3lv-$version-darwin-$MATRIX_ARCH.tar.gz.md5" "$package_name.tar.gz.md5"
          fi

          gh release upload "$VERSION_TAG" "$package_name.tar.gz"
          gh release upload "$VERSION_TAG" "$package_name.tar.gz.md5"
        env:
          GH_TOKEN: ${{ github.token }}
          MATRIX_OS: ${{ matrix.os }}
          MATRIX_ARCH: ${{ matrix.arch }}

  release:
    name: Release
    runs-on: elvia-runner
    needs: [draft-release, upload-binaries]
    if: ${{ github.event_name == 'push' }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Release if new version and not alpha or beta
        if: ${{ !contains(needs.build.outputs.version-tag, '-alpha') && !contains(needs.build.outputs.version-tag, '-beta') }}
        run: gh release edit "$VERSION_TAG" --draft=false --latest=true
        env:
          GH_TOKEN: ${{ github.token }}
          VERSION_TAG: ${{ needs.draft-release.outputs.version-tag }}
