name: Build and release

on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

jobs:
  build:
    name: Build
    runs-on: elvia-runner
    outputs:
      version-tag: ${{ steps.get-version.outputs.version_tag }}
      major-version-tag: ${{ steps.get-version.outputs.major_version_tag }}
    strategy:
      matrix:
        os: [linux, macos, windows]
        arch: [amd64]
        include:
          - os: macos
            arch: arm64
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Resolve version
        id: get-version
        run: |
          version=$(cat VERSION)
          echo "VERSION_TAG=v$version" >> "$GITHUB_OUTPUT"
          echo "MAJOR_VERSION_TAG=v$(echo $version | cut -d. -f1)" >> "$GITHUB_OUTPUT"

      - name: Package CLI
        run: make package-${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload artifacts (on push)
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v4
        with:
          name: '3lv-${{ matrix.os }}-${{ matrix.arch }}'
          path: '/tmp/3lv/dist'

  pre-release:
    name: Pre-release
    needs: [build]
    runs-on: elvia-runner
    if: ${{ github.event_name == 'push' }}
    outputs:
      new-version: ${{ steps.create-pre-release.outputs.new_version }}
    env:
      VERSION_TAG: ${{ needs.build.outputs.version-tag }}
      MAJOR_VERSION_TAG: ${{ needs.build.outputs.major-version-tag }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create pre-release if new version
        id: create-pre-release
        run: |
          latest_version=$(gh release list --json name,isLatest -q '.[] | select(.isLatest == true) | .name')
          if [[ "$latest_version" == "$VERSION_TAG" ]]; then
            echo "Version already released."
            echo 'new_version=false' >> "$GITHUB_OUTPUT"
            exit 0
          fi

          gh release create "$VERSION_TAG" --generate-notes --prerelease
          echo 'new_version=true' >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Override old major tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git fetch --tags
          git tag "$MAJOR_VERSION_TAG" "$VERSION_TAG" -f
          git push --tags -f

  upload-binaries:
    name: Upload binaries
    needs: [build, pre-release]
    runs-on: elvia-runner
    if: ${{ github.event_name == 'push' }}
    strategy:
      matrix:
        os: [linux, macos, windows]
        arch: [amd64]
        include:
          - os: macos
            arch: arm64
      fail-fast: false
    env:
      VERSION_TAG: ${{ needs.build.outputs.version-tag }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: '3lv-${{ matrix.os }}-${{ matrix.arch }}'

      - name: Upload binaries if new version
        if: ${{ needs.pre-release.outputs.new-version == 'true' }}
        run: |
          # Workaround for macOS binaries being named differently from their architecture (darwin)
          if [[ '${{ matrix.os }}' == 'macos' ]]; then
            mv '3lv-darwin-${{ matrix.arch }}.tar.gz' '3lv-macos-${{ matrix.arch }}.tar.gz'
            mv '3lv-darwin-${{ matrix.arch }}.tar.gz.md5' '3lv-macos-${{ matrix.arch }}.tar.gz.md5'
          fi

          # Workaround for Windows being packaged in zip files, not tarballs
          if [[ '${{ matrix.os }}' != 'windows' ]]; then
            gh release upload "$VERSION_TAG" '3lv-${{ matrix.os }}-${{ matrix.arch }}.tar.gz'
            gh release upload "$VERSION_TAG" '3lv-${{ matrix.os }}-${{ matrix.arch }}.tar.gz.md5'
          else
            gh release upload "$VERSION_TAG" '3lv-windows-${{ matrix.arch }}.zip'
            gh release upload "$VERSION_TAG" '3lv-windows-${{ matrix.arch }}.zip.md5'
          fi
        env:
          GH_TOKEN: ${{ github.token }}

  release:
    name: Release
    runs-on: elvia-runner
    needs: [pre-release, build, upload-binaries]
    if: ${{ github.event_name == 'push' }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Release if new version and not alpha or beta
        if: ${{ needs.pre-release.outputs.new-version == 'true' && !contains(needs.build.outputs.version-tag, '-alpha') && !contains(needs.build.outputs.version-tag, '-beta') }}
        run: gh release edit "$VERSION_TAG" --prerelease=false --latest
        env:
          GH_TOKEN: ${{ github.token }}
          VERSION_TAG: ${{ needs.build.outputs.version-tag }}
