name: End-to-End Tests

on:
  pull_request:
    branches: [trunk]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'install.sh'

jobs:
  e2e-tests:
    name: End-to-End Tests
    runs-on: elvia-runner
    strategy:
      matrix:
        command:
          - build
          - create
          - github-actions
          - init
          - scan
          - upgrade
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          cache-dependency-path: 'go.sum'
          go-version-file: 'go.mod'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Install CLI from source
        run: make install

      - name: Setup Python
        if: ${{ matrix.command == 'create' }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6

      - name: Install pipx and cookiecutter
        if: ${{ matrix.command == 'create' }}
        run: |
          sudo apt update
          sudo apt install -y pipx
          pipx install cookiecutter

      - name: Install uv
        if: ${{ matrix.command == 'create' }}
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: 'Run tests for ${{ matrix.command }} command'
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          "./tests/$COMMAND/run_tests.sh"
        env:
          # Increases rate-limit of when downloading 3lv from GitHub in tests for '3lv upgrade'.
          GITHUB_TOKEN: ${{ github.token }}
          COMMAND: ${{ matrix.command }}
