name: End-to-End Tests

on:
  pull_request:
    branches: [trunk]
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  e2e-tests:
    name: End-to-End Tests
    runs-on: elvia-runner-v2
    strategy:
      matrix:
        command:
          - build
          - create
          - github-actions
          - init
          - scan
          - upgrade
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: 'go.sum'
          go-version-file: 'go.mod'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Install CLI from source
        run: make install

      - name: Setup Python
        if: ${{ matrix.command == 'create' }}
        uses: actions/setup-python@v5

      - name: Install cookiecutter
        if: ${{ matrix.command == 'create' }}
        run: |
          sudo python3 -m pip install pipx
          sudo python3 -m pipx install cookiecutter --global

      - name: 'Run tests for ${{ matrix.command }} command'
        run: './tests/${{ matrix.command }}/run_tests.sh'
        env:
          # Increases rate-limit of when downloading 3lv from GitHub in tests for '3lv upgrade'.
          GITHUB_TOKEN: ${{ github.token }}
