name: End-to-End Tests

on:
  pull_request:
    branches: [trunk]
    paths-ignore:
      - 'README.md'

jobs:
  e2e-tests:
    name: End-to-End Tests
    runs-on: elvia-runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: 'go.sum'
          go-version-file: 'go.mod'

      - name: Install CLI
        uses: ./setup

      - name: Run tests for build command
        run: ./tests/build.sh

      - name: Run tests scan command
        run: ./tests/scan.sh
